app/exam/forms.py
from flask.ext.wtf import Form

from wtforms import StringField, SubmitField
from wtforms.validators import Required, Regexp


class WordForm(Form):
    group = StringField('group', validators=[Required(), Regexp('^[0-9]*$')])
    word = StringField('word', validators=[Required(), Regexp('^[A-Za-z\s\.]*$')])
    meaning = StringField('meaning', validators=[Required()])

    submit = SubmitField('submit')


class RespForm(Form):
    word1 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word2 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word3 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word4 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word5 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word6 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word7 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word8 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word9 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    word10 = StringField('', validators=[Required(), Regexp('^[A-Za-z]*$')])
    submit = SubmitField('submit')

    def __init__(self, nameli):
        word1 = StringField(str(nameli[0]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word2 = StringField(str(nameli[1]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word3 = StringField(str(nameli[2]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word4 = StringField(str(nameli[3]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word5 = StringField(str(nameli[4]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word6 = StringField(str(nameli[5]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word7 = StringField(str(nameli[6]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word8 = StringField(str(nameli[7]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word9 = StringField(str(nameli[8]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        word10 = StringField(str(nameli[9]), validators=[Required(), Regexp('^[A-Za-z]*$')])
        submit = SubmitField('submit')

app/exam/__init__.py
from flask import Blueprint

exam = Blueprint('exam', __name__)

from . import views, errors

app/exam/views.py
import random, re

from flask import render_template, request, flash, redirect, url_for, abort, make_response
from flask.ext.login import login_required

from flask.ext.wtf import Form
from wtforms import StringField, SubmitField

from .. import db
from ..models import InputWord

from . import exam
from .forms import WordForm, RespForm


@exam.route('/')
def index():
    group = db.session.query(InputWord.group).group_by(InputWord.group).all()

    length = len(group)

    if(length == 0):
        return redirect(url_for('exam.newWord'))

    return render_template('exam/exam.html', length=length)


@exam.route('/newWord', methods=['GET', 'POST'])
def newWord():
    form = WordForm()

    if form.validate_on_submit():
        new = InputWord(word=form.word.data, group=int(form.group.data), meaning=form.meaning.data)

        db.session.add(new)
        db.session.commit()

        flash('添加成功')

        return redirect(url_for('exam.newWord'))

    return render_template('exam/newword.html', form=form)


@exam.route('/<id>', methods=['GET', 'POST'])
def examIt(id):
    pawd = {1: '2120', 2: '2201', 3: '1011', 4: '2100', 5: '1200', 6: '0101'}

    try:
        id = int(id)
    except:
        abort(404)

    li = InputWord.query.filter_by(group=id).all()

    length = len(li)

    if(length < 10):
        abort(404)

    lsl = list(range(length))
    random.shuffle(lsl)
    print(lsl)

    class DynamicForm(Form):
        submit = SubmitField('submit')

    ls = ''
    for i in range(length):
        setattr(DynamicForm, 'word' + str(i+1), StringField(li[lsl[i]].meaning))
        ls += (str(lsl[i]) + ' ')

    form = DynamicForm()

    score = 0
    en = 0
    el = []

    if(form.validate_on_submit()):
        ls = request.cookies.get('ls')
        
        ns = '[0-9][0-9]*'

        lsl = re.findall(ns, ls)
        print(lsl)
        for i in range(length):

            if(getattr(form, 'word' + str(i+1)).data == li[int(lsl[i])].word):
                score += 1

            else:
                en += 1
                el.append(getattr(form, 'word' + str(i+1)).data)

        return render_template('exam/errorwords.html', en=en, el=el, pawd=pawd, id=id)

    resp = make_response(render_template('exam/exampage.html', li=li, length=length, form=form))

    resp.set_cookie('ls', ls, max_age=24*60*60)

    return resp

app/templates/exam/errorwords.html
{% extends 'base.html' %}

{% block title%} error words {% endblock %}

{% block page_content%}
    <div class="page-header">
        <h3> 错了{{en}}个 </h3>
    </div>

    <div>
        {% if en != 0 %}
        {% for i in range(en) %}
            <div>
                <p>{{el[i]}}</p>
            </div>
        {% endfor %}
        {% else %}
            <p>{{pawd[id]}}</p>
        {% endif %}
    </div>

{% endblock %}

app/templates/exam/exam.html
{% extends 'base.html' %}

{% block title %} select {% endblock %}

{% block page_content %}
    <div class="group-id">
    {% for i in range(length) %}    
            <a href="{{url_for('exam.examIt', id=i+1)}}"><span class="badge"> {{i+1}} </span>
    {% endfor %}
    </div>
{% endblock %}

app/templates/exam/exampage.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} examing {% endblock %}

{% block page_content %}
    {{wtf.quick_form(form)}}
{% endblock %}

app/templates/exam/newword.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} new word {% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1> 输入单词的组，单词和意思</h1>
    </div>

    <div class="container col-md-4">
        {{wtf.quick_form(form)}}
    </div>

{% endblock %}